//7B17-D35E-668E
GET https://vitaeapi.playdev.ulusofona.pt/curriculum/E919-3A7A-E42C
Accept: application/json
Authorization: Basic Z3lOREF5TURJTXpNM01EUTBPVEUzTWpNeU56azFPRFE6NU56SXlOVGt4TXpBeU1qa3lOelFOakkxTURJNU56azVNRFkwTURVM01nTXpNd016RTJNVGd6T1RnMk16SXhPQQ==
